package Character.Cultivation;

public enum CultivationRange {
    QI_CONDENSATION_FIRST(0),
    QI_CONDENSATION_SECOND(0),
    QI_CONDENSATION_THIRD(0),
    QI_CONDENSATION_FOURTH(0),
    QI_CONDENSATION_FIFTH(0),
    QI_CONDENSATION_SIXTH(0),
    QI_CONDENSATION_SEVENTH(0),
    QI_CONDENSATION_EIGHTH(0),
    QI_CONDENSATION_NINTH(0),
    QI_CONDENSATION_FIRST_UNREAL(0),
    QI_CONDENSATION_SECOND_UNREAL(0),
    QI_CONDENSATION_THIRD_UNREAL(0),
    QI_CONDENSATION_FOURTH_UNREAL(0),
    FOUNDATION_ESTABLISHMENT_INITIAL_FIRST(0),
    FOUNDATION_ESTABLISHMENT_INITIAL_SECOND(0),
    FOUNDATION_ESTABLISHMENT_INITIAL_THIRD(0),
    FOUNDATION_ESTABLISHMENT_INTERMEDIATE_FIRST(0),
    FOUNDATION_ESTABLISHMENT_INTERMEDIATE_SECOND(0),
    FOUNDATION_ESTABLISHMENT_INTERMEDIATE_THIRD(0),
    FOUNDATION_ESTABLISHMENT_ADVANCED_FIRST(0),
    FOUNDATION_ESTABLISHMENT_ADVANCED_SECOND(0),
    FOUNDATION_ESTABLISHMENT_ADVANCED_THIRD(0),
    FOUNDATION_ESTABLISHMENT_GREAT_PERFECTION_FIRST(0),
    FOUNDATION_ESTABLISHMENT_GREAT_PERFECTION_SECOND(0),
    FOUNDATION_ESTABLISHMENT_GREAT_PERFECTION_THIRD(0),
    FOUNDATION_ESTABLISHMENT_GREAT_PERFECTION_FOURTH(0),
    NASCENT_SOUL_EARLY(0),
    NASCENT_SOUL_INTERMEDIATE(0),
    NASCENT_SOUL_LATE(0),
    NASCENT_SOUL_GREAT_CIRCLE(0),
    SPIRIT_SEVERING_FIRST_SEVERING(0),
    SPIRIT_SEVERING_SECOND_SEVERING(0),
    SPIRIT_SEVERING_THIRD_SEVERING(0),
    DAO_SEEKING_EARLY(0),
    DAO_SEEKING_INTERMEDIATE(0),
    DAO_SEEKING_LATE(0),
    DAO_SEEKING_PEAK(0),
    IMMORTAL(0);

    private double statAverageThreshold = 0;

    private CultivationRange(int statAverageThreshold){
        this.statAverageThreshold = statAverageThreshold;
    }

    public double getStatAverageThreshold(){ return this.statAverageThreshold; }
}
