package Entities.Item.Components;

public enum EquippableZone {
    HEAD_TOP,
    HEAD_MIDDLE,
    HEAD_BOTTOM,

    NECK,
    
    SHOULDER_LEFT,
    SHOULDER_RIGHT,

    ARM_LEFT_SUPERIOR,
    ARM_LEFT_INFERIOR,
    ARM_LEFT_HAND,
    ARM_LEFT_FINGER_1,
    ARM_LEFT_FINGER_2,
    ARM_LEFT_FINGER_3,
    ARM_LEFT_FINGER_4,
    ARM_LEFT_FINGER_5,
    ARM_LEFT_FINGER_6,
    ARM_LEFT_FINGER_7,
    ARM_LEFT_FINGER_8,
    ARM_LEFT_FINGER_9,
    ARM_LEFT_FINGER_10,

    ARM_RIGHT_SUPERIOR,
    ARM_RIGHT_INFERIOR,
    ARM_RIGHT_HAND,
    ARM_RIGHT_FINGER_1,
    ARM_RIGHT_FINGER_2,
    ARM_RIGHT_FINGER_3,
    ARM_RIGHT_FINGER_4,
    ARM_RIGHT_FINGER_5,
    ARM_RIGHT_FINGER_6,
    ARM_RIGHT_FINGER_7,
    ARM_RIGHT_FINGER_8,
    ARM_RIGHT_FINGER_9,
    ARM_RIGHT_FINGER_10,

    BACK_TOP,
    BACK_MIDDLE,
    BACK_BOTTOM,
    
    CHEST_TOP,
    CHEST_MIDDLE,
    CHEST_BOTTOM,

    HIP_FRONT,
    HIP_BACK,

    LEG_LEFT_TOP,
    LEG_LEFT_BOTTOM,
    LEG_LEFT_FOOT,

    LEG_RIGHT_TOP,
    LEG_RIGHT_BOTTOM,
    LEG_RIGHT_FOOT,

    TAIL_TOP,
    TAIL_BOTTOM;

}
